setwd("C:/xampp/htdocs/Project")
library(qdapRegex)
library(tm)
library(ggplot2)
library(wordcloud)
preprocess = function(x)
{
  rm_twitter_url <- rm_(pattern=pastex("@rm_twitter_url", "@rm_url"))
  x <- rm_twitter_url(x)
  #x = x[!duplicated(x)]
  x = gsub("(RT|via)((?:\\b\\W*@\\w+)+)", "", x)
  x = gsub("@\\w+", "",x)
  x = gsub("[[:punct:]]","", x)
  x = gsub("[[:cntrl:]]", "", x)
  x = gsub("[[:digit:]]","",x)
  x = gsub("[ \t]{2,}","",x)
  x = gsub("^\\s+|\\s+$","",x)
  x = gsub("[^[:alnum:]]"," ",x)
  x = gsub("^ ", "", x)  # remove blank spaces at the beginning
  x = gsub(" $", "", x) # remove blank spaces at the end
  x = gsub(" *\\b[[:alpha:]]{1,2}\\b *", " ", x) # Remove 1-2 letter words
  #x = gsub('([[:alpha:]])\\1+', '\\1', x)
  x = gsub("^ +| +$|( ) +", "\\1", x)
  x = gsub(" ?(f|ht)tp(s?)://(.*)[.][a-z]+", "", x)
  return(x)
}
tweet <- read.csv("pre-processed.csv")
Neu <- read.csv("neutral-words.csv")
tweet[,1] <- preprocess(tweet[,1])
docs <- Corpus(VectorSource(tweet[,1]))
docs <- tm_map(docs, removeWords, stopwords("english"))
docs <- tm_map(docs, removeWords, Neu$content[1:3000])
docs <- tm_map(docs, removeWords, Neu$content[3001:4922])
docs <- tm_map(docs, stemDocument)
docs <- tm_map(docs, stripWhitespace)
docs <- tm_map(docs, PlainTextDocument)
dtm <- DocumentTermMatrix(docs)
tdm <- TermDocumentMatrix(docs)   
freq <- colSums(as.matrix(dtm))   
length(freq) 
ord <- order(freq)   
m <- as.matrix(dtm)   
dim(m)   
dtms <- removeSparseTerms(dtm, 0.1)
freq <- colSums(as.matrix(dtms))
freq <- sort(colSums(as.matrix(dtm)), decreasing=TRUE)
wf <- data.frame(word=names(freq), freq=freq)
p <- ggplot(subset(wf, freq>10), aes(word, freq))
p <- p + geom_bar(stat="identity")
p <- p + theme(axis.text.x=element_text(angle=45, hjust=1))

png(filename="freqwords.png", width=500, height=500)
plot(p)
dev.off()

png(filename="freqwordcloud.png", width=500, height=500)
wordcloud(names(freq), freq, min.freq=5, scale=c(5, 1), colors=brewer.pal(6, "Dark2"))
dev.off()
#png(filename="freqwordcloud1.png", width=500, height=500)
#wordcloud(names(freq), freq, max.words=60, rot.per=0.2, colors=brewer.pal(6, "Dark2"))
#dev.off()
